// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/jim-ww/itpec-sensei/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteAttempt provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteAttempt(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttempt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttempt'
type MockRepository_DeleteAttempt_Call struct {
	*mock.Call
}

// DeleteAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) DeleteAttempt(ctx interface{}, id interface{}) *MockRepository_DeleteAttempt_Call {
	return &MockRepository_DeleteAttempt_Call{Call: _e.mock.On("DeleteAttempt", ctx, id)}
}

func (_c *MockRepository_DeleteAttempt_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_DeleteAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteAttempt_Call) Return(err error) *MockRepository_DeleteAttempt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteAttempt_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRepository_DeleteAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttemptsForQuestions provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteAttemptsForQuestions(ctx context.Context, questionIDs []string) error {
	ret := _mock.Called(ctx, questionIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttemptsForQuestions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, questionIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteAttemptsForQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttemptsForQuestions'
type MockRepository_DeleteAttemptsForQuestions_Call struct {
	*mock.Call
}

// DeleteAttemptsForQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - questionIDs []string
func (_e *MockRepository_Expecter) DeleteAttemptsForQuestions(ctx interface{}, questionIDs interface{}) *MockRepository_DeleteAttemptsForQuestions_Call {
	return &MockRepository_DeleteAttemptsForQuestions_Call{Call: _e.mock.On("DeleteAttemptsForQuestions", ctx, questionIDs)}
}

func (_c *MockRepository_DeleteAttemptsForQuestions_Call) Run(run func(ctx context.Context, questionIDs []string)) *MockRepository_DeleteAttemptsForQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteAttemptsForQuestions_Call) Return(err error) *MockRepository_DeleteAttemptsForQuestions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteAttemptsForQuestions_Call) RunAndReturn(run func(ctx context.Context, questionIDs []string) error) *MockRepository_DeleteAttemptsForQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteSession(ctx context.Context, sessionID int64) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
func (_e *MockRepository_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockRepository_DeleteSession_Call {
	return &MockRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockRepository_DeleteSession_Call) Run(run func(ctx context.Context, sessionID int64)) *MockRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteSession_Call) Return(err error) *MockRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID int64) error) *MockRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// EndSession provides a mock function for the type MockRepository
func (_mock *MockRepository) EndSession(ctx context.Context, sessionID int64, exitReason string) error {
	ret := _mock.Called(ctx, sessionID, exitReason)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, sessionID, exitReason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type MockRepository_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
//   - exitReason string
func (_e *MockRepository_Expecter) EndSession(ctx interface{}, sessionID interface{}, exitReason interface{}) *MockRepository_EndSession_Call {
	return &MockRepository_EndSession_Call{Call: _e.mock.On("EndSession", ctx, sessionID, exitReason)}
}

func (_c *MockRepository_EndSession_Call) Run(run func(ctx context.Context, sessionID int64, exitReason string)) *MockRepository_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_EndSession_Call) Return(err error) *MockRepository_EndSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_EndSession_Call) RunAndReturn(run func(ctx context.Context, sessionID int64, exitReason string) error) *MockRepository_EndSession_Call {
	_c.Call.Return(run)
	return _c
}

// FailCounts provides a mock function for the type MockRepository
func (_mock *MockRepository) FailCounts(ctx context.Context, questionIDs []string) (map[string]int, error) {
	ret := _mock.Called(ctx, questionIDs)

	if len(ret) == 0 {
		panic("no return value specified for FailCounts")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]int, error)); ok {
		return returnFunc(ctx, questionIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]int); ok {
		r0 = returnFunc(ctx, questionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, questionIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FailCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailCounts'
type MockRepository_FailCounts_Call struct {
	*mock.Call
}

// FailCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - questionIDs []string
func (_e *MockRepository_Expecter) FailCounts(ctx interface{}, questionIDs interface{}) *MockRepository_FailCounts_Call {
	return &MockRepository_FailCounts_Call{Call: _e.mock.On("FailCounts", ctx, questionIDs)}
}

func (_c *MockRepository_FailCounts_Call) Run(run func(ctx context.Context, questionIDs []string)) *MockRepository_FailCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FailCounts_Call) Return(stringToInt map[string]int, err error) *MockRepository_FailCounts_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *MockRepository_FailCounts_Call) RunAndReturn(run func(ctx context.Context, questionIDs []string) (map[string]int, error)) *MockRepository_FailCounts_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAttempt provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertAttempt(ctx context.Context, sessionID int64, questionID string, answer string, correct bool, timedOut bool, timeTakenMs int, answeredAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, questionID, answer, correct, timedOut, timeTakenMs, answeredAt)

	if len(ret) == 0 {
		panic("no return value specified for InsertAttempt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, bool, bool, int, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, questionID, answer, correct, timedOut, timeTakenMs, answeredAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAttempt'
type MockRepository_InsertAttempt_Call struct {
	*mock.Call
}

// InsertAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
//   - questionID string
//   - answer string
//   - correct bool
//   - timedOut bool
//   - timeTakenMs int
//   - answeredAt time.Time
func (_e *MockRepository_Expecter) InsertAttempt(ctx interface{}, sessionID interface{}, questionID interface{}, answer interface{}, correct interface{}, timedOut interface{}, timeTakenMs interface{}, answeredAt interface{}) *MockRepository_InsertAttempt_Call {
	return &MockRepository_InsertAttempt_Call{Call: _e.mock.On("InsertAttempt", ctx, sessionID, questionID, answer, correct, timedOut, timeTakenMs, answeredAt)}
}

func (_c *MockRepository_InsertAttempt_Call) Run(run func(ctx context.Context, sessionID int64, questionID string, answer string, correct bool, timedOut bool, timeTakenMs int, answeredAt time.Time)) *MockRepository_InsertAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 time.Time
		if args[7] != nil {
			arg7 = args[7].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockRepository_InsertAttempt_Call) Return(err error) *MockRepository_InsertAttempt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertAttempt_Call) RunAndReturn(run func(ctx context.Context, sessionID int64, questionID string, answer string, correct bool, timedOut bool, timeTakenMs int, answeredAt time.Time) error) *MockRepository_InsertAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSession provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertSession(ctx context.Context, p repository.SessionParams) (int64, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertSession")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SessionParams) (int64, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SessionParams) int64); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.SessionParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_InsertSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSession'
type MockRepository_InsertSession_Call struct {
	*mock.Call
}

// InsertSession is a helper method to define mock.On call
//   - ctx context.Context
//   - p repository.SessionParams
func (_e *MockRepository_Expecter) InsertSession(ctx interface{}, p interface{}) *MockRepository_InsertSession_Call {
	return &MockRepository_InsertSession_Call{Call: _e.mock.On("InsertSession", ctx, p)}
}

func (_c *MockRepository_InsertSession_Call) Run(run func(ctx context.Context, p repository.SessionParams)) *MockRepository_InsertSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.SessionParams
		if args[1] != nil {
			arg1 = args[1].(repository.SessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertSession_Call) Return(n int64, err error) *MockRepository_InsertSession_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_InsertSession_Call) RunAndReturn(run func(ctx context.Context, p repository.SessionParams) (int64, error)) *MockRepository_InsertSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListAttempts provides a mock function for the type MockRepository
func (_mock *MockRepository) ListAttempts(ctx context.Context, filter repository.AttemptFilter, order repository.HistoryOrder, limit int) ([]repository.AttemptRow, error) {
	ret := _mock.Called(ctx, filter, order, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListAttempts")
	}

	var r0 []repository.AttemptRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.AttemptFilter, repository.HistoryOrder, int) ([]repository.AttemptRow, error)); ok {
		return returnFunc(ctx, filter, order, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.AttemptFilter, repository.HistoryOrder, int) []repository.AttemptRow); ok {
		r0 = returnFunc(ctx, filter, order, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.AttemptRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.AttemptFilter, repository.HistoryOrder, int) error); ok {
		r1 = returnFunc(ctx, filter, order, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAttempts'
type MockRepository_ListAttempts_Call struct {
	*mock.Call
}

// ListAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.AttemptFilter
//   - order repository.HistoryOrder
//   - limit int
func (_e *MockRepository_Expecter) ListAttempts(ctx interface{}, filter interface{}, order interface{}, limit interface{}) *MockRepository_ListAttempts_Call {
	return &MockRepository_ListAttempts_Call{Call: _e.mock.On("ListAttempts", ctx, filter, order, limit)}
}

func (_c *MockRepository_ListAttempts_Call) Run(run func(ctx context.Context, filter repository.AttemptFilter, order repository.HistoryOrder, limit int)) *MockRepository_ListAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.AttemptFilter
		if args[1] != nil {
			arg1 = args[1].(repository.AttemptFilter)
		}
		var arg2 repository.HistoryOrder
		if args[2] != nil {
			arg2 = args[2].(repository.HistoryOrder)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ListAttempts_Call) Return(attemptRows []repository.AttemptRow, err error) *MockRepository_ListAttempts_Call {
	_c.Call.Return(attemptRows, err)
	return _c
}

func (_c *MockRepository_ListAttempts_Call) RunAndReturn(run func(ctx context.Context, filter repository.AttemptFilter, order repository.HistoryOrder, limit int) ([]repository.AttemptRow, error)) *MockRepository_ListAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type MockRepository
func (_mock *MockRepository) ListSessions(ctx context.Context, order repository.HistoryOrder) ([]repository.SessionRecord, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []repository.SessionRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.HistoryOrder) ([]repository.SessionRecord, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.HistoryOrder) []repository.SessionRecord); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SessionRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.HistoryOrder) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockRepository_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - order repository.HistoryOrder
func (_e *MockRepository_Expecter) ListSessions(ctx interface{}, order interface{}) *MockRepository_ListSessions_Call {
	return &MockRepository_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, order)}
}

func (_c *MockRepository_ListSessions_Call) Run(run func(ctx context.Context, order repository.HistoryOrder)) *MockRepository_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.HistoryOrder
		if args[1] != nil {
			arg1 = args[1].(repository.HistoryOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListSessions_Call) Return(sessionRecords []repository.SessionRecord, err error) *MockRepository_ListSessions_Call {
	_c.Call.Return(sessionRecords, err)
	return _c
}

func (_c *MockRepository_ListSessions_Call) RunAndReturn(run func(ctx context.Context, order repository.HistoryOrder) ([]repository.SessionRecord, error)) *MockRepository_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAllProgress provides a mock function for the type MockRepository
func (_mock *MockRepository) ResetAllProgress(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetAllProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ResetAllProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAllProgress'
type MockRepository_ResetAllProgress_Call struct {
	*mock.Call
}

// ResetAllProgress is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ResetAllProgress(ctx interface{}) *MockRepository_ResetAllProgress_Call {
	return &MockRepository_ResetAllProgress_Call{Call: _e.mock.On("ResetAllProgress", ctx)}
}

func (_c *MockRepository_ResetAllProgress_Call) Run(run func(ctx context.Context)) *MockRepository_ResetAllProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ResetAllProgress_Call) Return(err error) *MockRepository_ResetAllProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ResetAllProgress_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_ResetAllProgress_Call {
	_c.Call.Return(run)
	return _c
}

// ReviewQueueQuestionIDs provides a mock function for the type MockRepository
func (_mock *MockRepository) ReviewQueueQuestionIDs(ctx context.Context) (map[string]bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReviewQueueQuestionIDs")
	}

	var r0 map[string]bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]bool); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ReviewQueueQuestionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewQueueQuestionIDs'
type MockRepository_ReviewQueueQuestionIDs_Call struct {
	*mock.Call
}

// ReviewQueueQuestionIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ReviewQueueQuestionIDs(ctx interface{}) *MockRepository_ReviewQueueQuestionIDs_Call {
	return &MockRepository_ReviewQueueQuestionIDs_Call{Call: _e.mock.On("ReviewQueueQuestionIDs", ctx)}
}

func (_c *MockRepository_ReviewQueueQuestionIDs_Call) Run(run func(ctx context.Context)) *MockRepository_ReviewQueueQuestionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ReviewQueueQuestionIDs_Call) Return(stringToBool map[string]bool, err error) *MockRepository_ReviewQueueQuestionIDs_Call {
	_c.Call.Return(stringToBool, err)
	return _c
}

func (_c *MockRepository_ReviewQueueQuestionIDs_Call) RunAndReturn(run func(ctx context.Context) (map[string]bool, error)) *MockRepository_ReviewQueueQuestionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SessionParamsByID provides a mock function for the type MockRepository
func (_mock *MockRepository) SessionParamsByID(ctx context.Context, sessionID int64) (repository.SessionParams, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SessionParamsByID")
	}

	var r0 repository.SessionParams
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (repository.SessionParams, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) repository.SessionParams); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(repository.SessionParams)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SessionParamsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionParamsByID'
type MockRepository_SessionParamsByID_Call struct {
	*mock.Call
}

// SessionParamsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
func (_e *MockRepository_Expecter) SessionParamsByID(ctx interface{}, sessionID interface{}) *MockRepository_SessionParamsByID_Call {
	return &MockRepository_SessionParamsByID_Call{Call: _e.mock.On("SessionParamsByID", ctx, sessionID)}
}

func (_c *MockRepository_SessionParamsByID_Call) Run(run func(ctx context.Context, sessionID int64)) *MockRepository_SessionParamsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SessionParamsByID_Call) Return(sessionParams repository.SessionParams, err error) *MockRepository_SessionParamsByID_Call {
	_c.Call.Return(sessionParams, err)
	return _c
}

func (_c *MockRepository_SessionParamsByID_Call) RunAndReturn(run func(ctx context.Context, sessionID int64) (repository.SessionParams, error)) *MockRepository_SessionParamsByID_Call {
	_c.Call.Return(run)
	return _c
}
