// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
	"time"
)

type Attempt struct {
	ID          int64
	SessionID   int64
	QuestionID  string
	Answer      string
	Correct     bool
	TimedOut    bool
	TimeTakenMs sql.NullInt64
	AnsweredAt  time.Time
}

type QuestionSr struct {
	QuestionID     string
	Box            int64
	DueAt          time.Time
	LastReviewedAt time.Time
}

type Session struct {
	ID                       int64
	StartedAt                time.Time
	EndedAt                  sql.NullTime
	ExamType                 string
	ExamID                   sql.NullString
	Mode                     string
	OrderStrategy            string
	TimeLimitSeconds         sql.NullInt64
	QuestionTimeLimitSeconds sql.NullInt64
	ExitReason               sql.NullString
	PlannedQuestions         sql.NullString
	Topic                    sql.NullString
	Part                     sql.NullString
	QuestionLimit            sql.NullInt64
	QuestionNumber           sql.NullInt64
}
