// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteAllAttempts = `-- name: DeleteAllAttempts :exec
DELETE FROM attempts
`

func (q *Queries) DeleteAllAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAttempts)
	return err
}

const deleteAllQuestionSRS = `-- name: DeleteAllQuestionSRS :exec
DELETE FROM question_srs
`

func (q *Queries) DeleteAllQuestionSRS(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllQuestionSRS)
	return err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM sessions
`

func (q *Queries) DeleteAllSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessions)
	return err
}

const deleteAttempt = `-- name: DeleteAttempt :exec
DELETE FROM attempts WHERE id = ?
`

func (q *Queries) DeleteAttempt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttempt, id)
	return err
}

const deleteAttemptsBySession = `-- name: DeleteAttemptsBySession :exec
DELETE FROM attempts WHERE session_id = ?
`

func (q *Queries) DeleteAttemptsBySession(ctx context.Context, sessionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttemptsBySession, sessionID)
	return err
}

const deleteAttemptsForQuestions = `-- name: DeleteAttemptsForQuestions :exec
DELETE FROM attempts WHERE question_id IN (/*SLICE:question_ids*/?)
`

func (q *Queries) DeleteAttemptsForQuestions(ctx context.Context, questionIds []string) error {
	query := deleteAttemptsForQuestions
	var queryParams []interface{}
	if len(questionIds) > 0 {
		for _, v := range questionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:question_ids*/?", strings.Repeat(",?", len(questionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:question_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteQuestionSRSForQuestions = `-- name: DeleteQuestionSRSForQuestions :exec
DELETE FROM question_srs WHERE question_id IN (/*SLICE:question_ids*/?)
`

func (q *Queries) DeleteQuestionSRSForQuestions(ctx context.Context, questionIds []string) error {
	query := deleteQuestionSRSForQuestions
	var queryParams []interface{}
	if len(questionIds) > 0 {
		for _, v := range questionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:question_ids*/?", strings.Repeat(",?", len(questionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:question_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :execrows
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dueQuestionIDs = `-- name: DueQuestionIDs :many
SELECT question_id FROM question_srs WHERE due_at <= ?
`

func (q *Queries) DueQuestionIDs(ctx context.Context, dueAt time.Time) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, dueQuestionIDs, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var question_id string
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endSession = `-- name: EndSession :exec
UPDATE sessions SET ended_at = ?, exit_reason = ? WHERE id = ?
`

type EndSessionParams struct {
	EndedAt    sql.NullTime
	ExitReason sql.NullString
	ID         int64
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) error {
	_, err := q.db.ExecContext(ctx, endSession, arg.EndedAt, arg.ExitReason, arg.ID)
	return err
}

const failCounts = `-- name: FailCounts :many
SELECT question_id, COUNT(*) AS n FROM attempts WHERE correct = 0 AND question_id IN (/*SLICE:question_ids*/?) GROUP BY question_id
`

type FailCountsRow struct {
	QuestionID string
	N          int64
}

func (q *Queries) FailCounts(ctx context.Context, questionIds []string) ([]FailCountsRow, error) {
	query := failCounts
	var queryParams []interface{}
	if len(questionIds) > 0 {
		for _, v := range questionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:question_ids*/?", strings.Repeat(",?", len(questionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:question_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailCountsRow
	for rows.Next() {
		var i FailCountsRow
		if err := rows.Scan(&i.QuestionID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastAttemptAny = `-- name: GetLastAttemptAny :one
SELECT id, session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at
FROM attempts ORDER BY answered_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLastAttemptAny(ctx context.Context) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, getLastAttemptAny)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.QuestionID,
		&i.Answer,
		&i.Correct,
		&i.TimedOut,
		&i.TimeTakenMs,
		&i.AnsweredAt,
	)
	return i, err
}

const getLastAttemptForSession = `-- name: GetLastAttemptForSession :one
SELECT id, session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at
FROM attempts WHERE session_id = ? ORDER BY answered_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLastAttemptForSession(ctx context.Context, sessionID int64) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, getLastAttemptForSession, sessionID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.QuestionID,
		&i.Answer,
		&i.Correct,
		&i.TimedOut,
		&i.TimeTakenMs,
		&i.AnsweredAt,
	)
	return i, err
}

const getQuestionSRS = `-- name: GetQuestionSRS :one

SELECT question_id, box, due_at, last_reviewed_at FROM question_srs WHERE question_id = ?
`

// SRS (Leitner scheduling) --
func (q *Queries) GetQuestionSRS(ctx context.Context, questionID string) (QuestionSr, error) {
	row := q.db.QueryRowContext(ctx, getQuestionSRS, questionID)
	var i QuestionSr
	err := row.Scan(
		&i.QuestionID,
		&i.Box,
		&i.DueAt,
		&i.LastReviewedAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec

INSERT INTO attempts (session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAttemptParams struct {
	SessionID   int64
	QuestionID  string
	Answer      string
	Correct     bool
	TimedOut    bool
	TimeTakenMs sql.NullInt64
	AnsweredAt  time.Time
}

// Attempts --
//
// These return unordered rows; sorting by newest/oldest and applying a limit
// both happen in Go (repo.go), not here - this app runs against a single
// local user's data (at most a few thousand attempts), so fetch-then-sort-in-
// Go is simpler than juggling per-direction SQL variants, with no meaningful
// cost.
//
// NOTE: keep this file ASCII-only. sqlc's sqlite-engine slice() rewriter has
// a byte-offset bug: a multi-byte UTF-8 character (e.g. an em-dash) anywhere
// earlier in the file shifts byte offsets and silently corrupts the
// generated SQL for every later sqlc.slice() query. Also keep each
// sqlc.slice() query on a single line with no comment directly above it -
// both also corrupt the rewrite.
func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertAttempt,
		arg.SessionID,
		arg.QuestionID,
		arg.Answer,
		arg.Correct,
		arg.TimedOut,
		arg.TimeTakenMs,
		arg.AnsweredAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :one

INSERT INTO sessions (started_at, exam_type, exam_id, topic, part, mode, order_strategy,
                       time_limit_seconds, question_time_limit_seconds, question_limit, question_number)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertSessionParams struct {
	StartedAt                time.Time
	ExamType                 string
	ExamID                   sql.NullString
	Topic                    sql.NullString
	Part                     sql.NullString
	Mode                     string
	OrderStrategy            string
	TimeLimitSeconds         sql.NullInt64
	QuestionTimeLimitSeconds sql.NullInt64
	QuestionLimit            sql.NullInt64
	QuestionNumber           sql.NullInt64
}

// Sessions --
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSession,
		arg.StartedAt,
		arg.ExamType,
		arg.ExamID,
		arg.Topic,
		arg.Part,
		arg.Mode,
		arg.OrderStrategy,
		arg.TimeLimitSeconds,
		arg.QuestionTimeLimitSeconds,
		arg.QuestionLimit,
		arg.QuestionNumber,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAllAttempts = `-- name: ListAllAttempts :many
SELECT id, session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at
FROM attempts
`

func (q *Queries) ListAllAttempts(ctx context.Context) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAllAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.QuestionID,
			&i.Answer,
			&i.Correct,
			&i.TimedOut,
			&i.TimeTakenMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAttemptsSince = `-- name: ListAllAttemptsSince :many
SELECT id, session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at
FROM attempts WHERE answered_at >= ?
`

func (q *Queries) ListAllAttemptsSince(ctx context.Context, answeredAt time.Time) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAllAttemptsSince, answeredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.QuestionID,
			&i.Answer,
			&i.Correct,
			&i.TimedOut,
			&i.TimeTakenMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByQuestionIDs = `-- name: ListAttemptsByQuestionIDs :many
SELECT id, session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at FROM attempts WHERE question_id IN (/*SLICE:question_ids*/?)
`

func (q *Queries) ListAttemptsByQuestionIDs(ctx context.Context, questionIds []string) ([]Attempt, error) {
	query := listAttemptsByQuestionIDs
	var queryParams []interface{}
	if len(questionIds) > 0 {
		for _, v := range questionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:question_ids*/?", strings.Repeat(",?", len(questionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:question_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.QuestionID,
			&i.Answer,
			&i.Correct,
			&i.TimedOut,
			&i.TimeTakenMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByQuestionIDsSince = `-- name: ListAttemptsByQuestionIDsSince :many
SELECT id, session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at FROM attempts WHERE question_id IN (/*SLICE:question_ids*/?) AND answered_at >= ?
`

type ListAttemptsByQuestionIDsSinceParams struct {
	QuestionIds []string
	AnsweredAt  time.Time
}

func (q *Queries) ListAttemptsByQuestionIDsSince(ctx context.Context, arg ListAttemptsByQuestionIDsSinceParams) ([]Attempt, error) {
	query := listAttemptsByQuestionIDsSince
	var queryParams []interface{}
	if len(arg.QuestionIds) > 0 {
		for _, v := range arg.QuestionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:question_ids*/?", strings.Repeat(",?", len(arg.QuestionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:question_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.AnsweredAt)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.QuestionID,
			&i.Answer,
			&i.Correct,
			&i.TimedOut,
			&i.TimeTakenMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsBySession = `-- name: ListAttemptsBySession :many
SELECT id, session_id, question_id, answer, correct, timed_out, time_taken_ms, answered_at
FROM attempts WHERE session_id = ?
`

func (q *Queries) ListAttemptsBySession(ctx context.Context, sessionID int64) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.QuestionID,
			&i.Answer,
			&i.Correct,
			&i.TimedOut,
			&i.TimeTakenMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.started_at, s.ended_at, s.exam_type, s.exam_id, s.mode, s.order_strategy,
       s.time_limit_seconds, s.question_time_limit_seconds, s.exit_reason,
       COUNT(a.id) AS answered, COALESCE(SUM(CASE WHEN a.correct THEN 1 ELSE 0 END), 0) AS correct
FROM sessions s
LEFT JOIN attempts a ON a.session_id = s.id
GROUP BY s.id
`

type ListSessionsRow struct {
	ID                       int64
	StartedAt                time.Time
	EndedAt                  sql.NullTime
	ExamType                 string
	ExamID                   sql.NullString
	Mode                     string
	OrderStrategy            string
	TimeLimitSeconds         sql.NullInt64
	QuestionTimeLimitSeconds sql.NullInt64
	ExitReason               sql.NullString
	Answered                 int64
	Correct                  interface{}
}

// Not ordered here; ListSessions in repo.go sorts by StartedAt per the
// requested direction (see the Attempts comment above for why).
func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExamType,
			&i.ExamID,
			&i.Mode,
			&i.OrderStrategy,
			&i.TimeLimitSeconds,
			&i.QuestionTimeLimitSeconds,
			&i.ExitReason,
			&i.Answered,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionParamsByID = `-- name: SessionParamsByID :one
SELECT exam_type, exam_id, topic, part, mode, order_strategy,
       time_limit_seconds, question_time_limit_seconds,
       question_limit, question_number
FROM sessions WHERE id = ?
`

type SessionParamsByIDRow struct {
	ExamType                 string
	ExamID                   sql.NullString
	Topic                    sql.NullString
	Part                     sql.NullString
	Mode                     string
	OrderStrategy            string
	TimeLimitSeconds         sql.NullInt64
	QuestionTimeLimitSeconds sql.NullInt64
	QuestionLimit            sql.NullInt64
	QuestionNumber           sql.NullInt64
}

func (q *Queries) SessionParamsByID(ctx context.Context, id int64) (SessionParamsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, sessionParamsByID, id)
	var i SessionParamsByIDRow
	err := row.Scan(
		&i.ExamType,
		&i.ExamID,
		&i.Topic,
		&i.Part,
		&i.Mode,
		&i.OrderStrategy,
		&i.TimeLimitSeconds,
		&i.QuestionTimeLimitSeconds,
		&i.QuestionLimit,
		&i.QuestionNumber,
	)
	return i, err
}

const upsertQuestionSRS = `-- name: UpsertQuestionSRS :exec
INSERT INTO question_srs (question_id, box, due_at, last_reviewed_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(question_id) DO UPDATE SET box = excluded.box, due_at = excluded.due_at, last_reviewed_at = excluded.last_reviewed_at
`

type UpsertQuestionSRSParams struct {
	QuestionID     string
	Box            int64
	DueAt          time.Time
	LastReviewedAt time.Time
}

func (q *Queries) UpsertQuestionSRS(ctx context.Context, arg UpsertQuestionSRSParams) error {
	_, err := q.db.ExecContext(ctx, upsertQuestionSRS,
		arg.QuestionID,
		arg.Box,
		arg.DueAt,
		arg.LastReviewedAt,
	)
	return err
}
