// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"time"
)

type Querier interface {
	DeleteAllAttempts(ctx context.Context) error
	DeleteAllQuestionSRS(ctx context.Context) error
	DeleteAllSessions(ctx context.Context) error
	DeleteAttempt(ctx context.Context, id int64) error
	DeleteAttemptsBySession(ctx context.Context, sessionID int64) error
	DeleteAttemptsForQuestions(ctx context.Context, questionIds []string) error
	DeleteQuestionSRSForQuestions(ctx context.Context, questionIds []string) error
	DeleteSessionByID(ctx context.Context, id int64) (int64, error)
	DueQuestionIDs(ctx context.Context, dueAt time.Time) ([]string, error)
	EndSession(ctx context.Context, arg EndSessionParams) error
	FailCounts(ctx context.Context, questionIds []string) ([]FailCountsRow, error)
	GetLastAttemptAny(ctx context.Context) (Attempt, error)
	GetLastAttemptForSession(ctx context.Context, sessionID int64) (Attempt, error)
	// SRS (Leitner scheduling) --
	GetQuestionSRS(ctx context.Context, questionID string) (QuestionSr, error)
	// Attempts --
	//
	// These return unordered rows; sorting by newest/oldest and applying a limit
	// both happen in Go (repo.go), not here - this app runs against a single
	// local user's data (at most a few thousand attempts), so fetch-then-sort-in-
	// Go is simpler than juggling per-direction SQL variants, with no meaningful
	// cost.
	//
	// NOTE: keep this file ASCII-only. sqlc's sqlite-engine slice() rewriter has
	// a byte-offset bug: a multi-byte UTF-8 character (e.g. an em-dash) anywhere
	// earlier in the file shifts byte offsets and silently corrupts the
	// generated SQL for every later sqlc.slice() query. Also keep each
	// sqlc.slice() query on a single line with no comment directly above it -
	// both also corrupt the rewrite.
	InsertAttempt(ctx context.Context, arg InsertAttemptParams) error
	// Sessions --
	InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error)
	ListAllAttempts(ctx context.Context) ([]Attempt, error)
	ListAllAttemptsSince(ctx context.Context, answeredAt time.Time) ([]Attempt, error)
	ListAttemptsByQuestionIDs(ctx context.Context, questionIds []string) ([]Attempt, error)
	ListAttemptsByQuestionIDsSince(ctx context.Context, arg ListAttemptsByQuestionIDsSinceParams) ([]Attempt, error)
	ListAttemptsBySession(ctx context.Context, sessionID int64) ([]Attempt, error)
	// Not ordered here; ListSessions in repo.go sorts by StartedAt per the
	// requested direction (see the Attempts comment above for why).
	ListSessions(ctx context.Context) ([]ListSessionsRow, error)
	SessionParamsByID(ctx context.Context, id int64) (SessionParamsByIDRow, error)
	UpsertQuestionSRS(ctx context.Context, arg UpsertQuestionSRSParams) error
}

var _ Querier = (*Queries)(nil)
