// Package sqlite is the sqlite-backed repository.Repository implementation.
// The SQL itself is generated by sqlc from schema.sql/queries.sql (see
// queries.sql.go, models.go, db.go, querier.go — all "DO NOT EDIT"); this
// file only adapts the generated Queries to the repository.Repository
// interface, translating between sqlc's generated types and package
// repository's types, and orchestrating the one operation (DeleteSession)
// that needs a transaction across two generated queries.
//
//go:generate sqlc generate
package sqlite

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"sort"
	"time"

	_ "modernc.org/sqlite"

	"github.com/jim-ww/itpec-sensei/internal/repository"
)

// Repository implements repository.Repository over db.
type Repository struct {
	db *sql.DB
	q  *Queries
}

// NewRepository wraps db (as returned by Open) as a repository.Repository.
func NewRepository(db *sql.DB) repository.Repository {
	return &Repository{db: db, q: New(db)}
}

func toAttemptRow(a Attempt) repository.AttemptRow {
	return repository.AttemptRow{
		ID:          a.ID,
		QuestionID:  a.QuestionID,
		Answer:      a.Answer,
		Correct:     a.Correct,
		TimedOut:    a.TimedOut,
		TimeTakenMs: int(a.TimeTakenMs.Int64),
		AnsweredAt:  a.AnsweredAt,
	}
}

func sortAndLimitAttempts(rows []repository.AttemptRow, order repository.HistoryOrder, limit int) []repository.AttemptRow {
	sort.Slice(rows, func(i, j int) bool {
		if !rows[i].AnsweredAt.Equal(rows[j].AnsweredAt) {
			if order == repository.HistoryOldestFirst {
				return rows[i].AnsweredAt.Before(rows[j].AnsweredAt)
			}
			return rows[i].AnsweredAt.After(rows[j].AnsweredAt)
		}
		if order == repository.HistoryOldestFirst {
			return rows[i].ID < rows[j].ID
		}
		return rows[i].ID > rows[j].ID
	})
	if limit > 0 && limit < len(rows) {
		rows = rows[:limit]
	}
	return rows
}

func (r *Repository) InsertAttempt(ctx context.Context, sessionID int64, questionID, answer string, correct, timedOut bool, timeTakenMs int, answeredAt time.Time) error {
	return r.q.InsertAttempt(ctx, InsertAttemptParams{
		SessionID:   sessionID,
		QuestionID:  questionID,
		Answer:      answer,
		Correct:     correct,
		TimedOut:    timedOut,
		TimeTakenMs: nullableInt64(timeTakenMs),
		AnsweredAt:  answeredAt,
	})
}

func (r *Repository) ListAttempts(ctx context.Context, filter repository.AttemptFilter, order repository.HistoryOrder, limit int) ([]repository.AttemptRow, error) {
	var rows []Attempt
	var err error
	switch {
	case filter.SessionID != 0:
		rows, err = r.q.ListAttemptsBySession(ctx, filter.SessionID)
	case filter.QuestionIDs != nil:
		if len(filter.QuestionIDs) == 0 {
			// An empty (non-nil) set means "filter to nothing", not "no filter".
			return nil, nil
		}
		if filter.Since != nil {
			rows, err = r.q.ListAttemptsByQuestionIDsSince(ctx, ListAttemptsByQuestionIDsSinceParams{
				QuestionIds: filter.QuestionIDs,
				AnsweredAt:  *filter.Since,
			})
		} else {
			rows, err = r.q.ListAttemptsByQuestionIDs(ctx, filter.QuestionIDs)
		}
	default:
		if filter.Since != nil {
			rows, err = r.q.ListAllAttemptsSince(ctx, *filter.Since)
		} else {
			rows, err = r.q.ListAllAttempts(ctx)
		}
	}
	if err != nil {
		return nil, fmt.Errorf("query attempts: %w", err)
	}

	out := make([]repository.AttemptRow, len(rows))
	for i, a := range rows {
		out[i] = toAttemptRow(a)
	}
	return sortAndLimitAttempts(out, order, limit), nil
}

func (r *Repository) DeleteAttempt(ctx context.Context, id int64) error {
	return r.q.DeleteAttempt(ctx, id)
}

func (r *Repository) DueQuestionIDs(ctx context.Context, asOf time.Time) (map[string]bool, error) {
	ids, err := r.q.DueQuestionIDs(ctx, asOf)
	if err != nil {
		return nil, fmt.Errorf("query due questions: %w", err)
	}
	out := make(map[string]bool, len(ids))
	for _, id := range ids {
		out[id] = true
	}
	return out, nil
}

func (r *Repository) GetQuestionSRS(ctx context.Context, questionID string) (repository.QuestionSRS, bool, error) {
	row, err := r.q.GetQuestionSRS(ctx, questionID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return repository.QuestionSRS{}, false, nil
		}
		return repository.QuestionSRS{}, false, fmt.Errorf("get question srs: %w", err)
	}
	return repository.QuestionSRS{
		Box:            int(row.Box),
		DueAt:          row.DueAt,
		LastReviewedAt: row.LastReviewedAt,
	}, true, nil
}

func (r *Repository) UpsertQuestionSRS(ctx context.Context, questionID string, state repository.QuestionSRS) error {
	if err := r.q.UpsertQuestionSRS(ctx, UpsertQuestionSRSParams{
		QuestionID:     questionID,
		Box:            int64(state.Box),
		DueAt:          state.DueAt,
		LastReviewedAt: state.LastReviewedAt,
	}); err != nil {
		return fmt.Errorf("upsert question srs: %w", err)
	}
	return nil
}

func (r *Repository) FailCounts(ctx context.Context, questionIDs []string) (map[string]int, error) {
	if len(questionIDs) == 0 {
		return nil, nil
	}
	rows, err := r.q.FailCounts(ctx, questionIDs)
	if err != nil {
		return nil, fmt.Errorf("query fail counts: %w", err)
	}
	out := make(map[string]int, len(rows))
	for _, row := range rows {
		out[row.QuestionID] = int(row.N)
	}
	return out, nil
}

func (r *Repository) InsertSession(ctx context.Context, p repository.SessionParams) (int64, error) {
	id, err := r.q.InsertSession(ctx, InsertSessionParams{
		StartedAt:                time.Now().UTC(),
		ExamType:                 p.ExamType,
		ExamID:                   nullableString(p.ExamID),
		Topic:                    nullableString(p.Topic),
		Part:                     nullableString(p.Part),
		Mode:                     p.Mode,
		OrderStrategy:            p.OrderStrategy,
		TimeLimitSeconds:         nullableInt64Ptr(p.TimeLimitSeconds),
		QuestionTimeLimitSeconds: nullableInt64Ptr(p.QuestionTimeLimitSeconds),
		QuestionLimit:            nullableInt64(p.QuestionLimit),
		QuestionNumber:           nullableInt64(p.QuestionNumber),
	})
	if err != nil {
		return 0, fmt.Errorf("start session: %w", err)
	}
	return id, nil
}

func (r *Repository) EndSession(ctx context.Context, sessionID int64, exitReason string) error {
	return r.q.EndSession(ctx, EndSessionParams{
		EndedAt:    sql.NullTime{Time: time.Now().UTC(), Valid: true},
		ExitReason: nullableString(exitReason),
		ID:         sessionID,
	})
}

func (r *Repository) DeleteSession(ctx context.Context, sessionID int64) error {
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}
	defer tx.Rollback()

	qtx := New(tx)
	if err := qtx.DeleteAttemptsBySession(ctx, sessionID); err != nil {
		return fmt.Errorf("delete session attempts: %w", err)
	}
	n, err := qtx.DeleteSessionByID(ctx, sessionID)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("session %d not found", sessionID)
	}
	return tx.Commit()
}

func (r *Repository) SessionParamsByID(ctx context.Context, sessionID int64) (repository.SessionParams, error) {
	row, err := r.q.SessionParamsByID(ctx, sessionID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return repository.SessionParams{}, fmt.Errorf("session %d not found", sessionID)
		}
		return repository.SessionParams{}, fmt.Errorf("get session params: %w", err)
	}

	p := repository.SessionParams{
		ExamType:       row.ExamType,
		ExamID:         row.ExamID.String,
		Topic:          row.Topic.String,
		Part:           row.Part.String,
		Mode:           row.Mode,
		OrderStrategy:  row.OrderStrategy,
		QuestionLimit:  int(row.QuestionLimit.Int64),
		QuestionNumber: int(row.QuestionNumber.Int64),
	}
	if row.TimeLimitSeconds.Valid {
		v := int(row.TimeLimitSeconds.Int64)
		p.TimeLimitSeconds = &v
	}
	if row.QuestionTimeLimitSeconds.Valid {
		v := int(row.QuestionTimeLimitSeconds.Int64)
		p.QuestionTimeLimitSeconds = &v
	}
	return p, nil
}

func (r *Repository) ListSessions(ctx context.Context, order repository.HistoryOrder) ([]repository.SessionRecord, error) {
	rows, err := r.q.ListSessions(ctx)
	if err != nil {
		return nil, fmt.Errorf("query sessions: %w", err)
	}

	out := make([]repository.SessionRecord, len(rows))
	for i, row := range rows {
		rec := repository.SessionRecord{
			ID:            row.ID,
			StartedAt:     row.StartedAt,
			ExamType:      row.ExamType,
			ExamID:        row.ExamID.String,
			Mode:          row.Mode,
			OrderStrategy: row.OrderStrategy,
			ExitReason:    row.ExitReason.String,
			Answered:      int(row.Answered),
			Correct:       toInt(row.Correct),
		}
		if row.EndedAt.Valid {
			t := row.EndedAt.Time
			rec.EndedAt = &t
		}
		if row.TimeLimitSeconds.Valid {
			v := int(row.TimeLimitSeconds.Int64)
			rec.TimeLimitSeconds = &v
		}
		if row.QuestionTimeLimitSeconds.Valid {
			v := int(row.QuestionTimeLimitSeconds.Int64)
			rec.QuestionTimeLimitSeconds = &v
		}
		out[i] = rec
	}

	sort.Slice(out, func(i, j int) bool {
		if order == repository.HistoryOldestFirst {
			return out[i].StartedAt.Before(out[j].StartedAt)
		}
		return out[i].StartedAt.After(out[j].StartedAt)
	})
	return out, nil
}

func (r *Repository) ResetAllProgress(ctx context.Context) error {
	if err := r.q.DeleteAllAttempts(ctx); err != nil {
		return fmt.Errorf("reset attempts: %w", err)
	}
	if err := r.q.DeleteAllSessions(ctx); err != nil {
		return fmt.Errorf("reset sessions: %w", err)
	}
	if err := r.q.DeleteAllQuestionSRS(ctx); err != nil {
		return fmt.Errorf("reset srs: %w", err)
	}
	return nil
}

func (r *Repository) DeleteAttemptsForQuestions(ctx context.Context, questionIDs []string) error {
	if len(questionIDs) == 0 {
		return nil
	}
	if err := r.q.DeleteAttemptsForQuestions(ctx, questionIDs); err != nil {
		return fmt.Errorf("reset scoped attempts: %w", err)
	}
	if err := r.q.DeleteQuestionSRSForQuestions(ctx, questionIDs); err != nil {
		return fmt.Errorf("reset scoped srs: %w", err)
	}
	return nil
}

// toInt converts the driver-boxed COALESCE(SUM(...), 0) result (sqlc can't
// infer a concrete type for it, hence the interface{} in ListSessionsRow) to
// an int.
func toInt(v any) int {
	switch n := v.(type) {
	case int64:
		return int(n)
	case int:
		return n
	case float64:
		return int(n)
	default:
		return 0
	}
}

func nullableString(s string) sql.NullString {
	if s == "" {
		return sql.NullString{}
	}
	return sql.NullString{String: s, Valid: true}
}

func nullableInt64(n int) sql.NullInt64 {
	if n == 0 {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: int64(n), Valid: true}
}

func nullableInt64Ptr(n *int) sql.NullInt64 {
	if n == nil {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: int64(*n), Valid: true}
}
